### ISSUE TITLE
Angle class for better handling of angle quantities

### ISSUE THREAD

**Issue by drpjm** [usdot-fhwa-stol/cooperative-perception-core#11]
### Type of issue

- [ ] Anomaly report (something appears to not work correctly)
- [X] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn't fall into either of the above categories)

### Descriptive summary

When using sampling techniques with angles, one has to be careful with managing how angles are added and subtracted as they range only on [0, 2pi). This feature would allow CP model types, such as `CtrvState` and `CtraState`, to correctly handle angles using these operations, which is critical for our unscented transform operations.

### Steps to reproduce the actual behavior

1. Do this
2. Then do this
3. ...

### Related work

After some white-boarding, we decided it would make sense to represent angles using complex numbers to take advantage of concepts like the [circular mean](https://en.wikipedia.org/wiki/Circular_mean).

**Comment by msmcconnell** [comment]
Resolved by above PR
