### ISSUE TITLE
Missing temporal alignment algorithm

### ISSUE THREAD

**Issue by adamlm** [usdot-fhwa-stol/cooperative-perception-core#14]
### Type of issue

- [ ] Anomaly report (something appears to not work correctly)
- [X] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn't fall into either of the above categories)

### Descriptive summary

The project is missing temporal alignment, which is a critical component to perception. Individual sensors report their measurements at different time stamps. To plan motion safely and accurately, the planner needs all object states to be aligned to the same time.

Here are the necessary steps:
* generate sigma points from current mean state vector and covariance matrix
* propagate sigma points using process model (optionally using process noise vector)
* approximate new mean state vector and covariance matrix from propagated sigma points

### CARMA version where this issue was discovered

N/A

### Expected behavior

N/A

### Actual behavior

N/A

### Steps to reproduce the actual behavior

N/A

### Related work

N/A

**Comment by drpjm** [comment]
This issue was resolved with PR #20.
